from app.schemas.admin import (
    GlobalStatsResponse, PipelineStatsResponse, HealthAnalyticsResponse, 
    PaymentMethodResponse, MemberStatsResponse, MemberPrivilegesResponse, 
    MemberPrivilegesUpdate, MemberRegisterRequest, MemberRegisterResponse,
    PaymentMethodCreate, SubscriptionUpgradeRequest
)
from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    TokenPayload,
    RefreshRequest,
    UserResponse,
    AdminLoginResponse,
    AdminLoginResponseUser,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    CandidateLoginRequest,
    CandidateAuthResponse,
)
from app.schemas.candidate import (
    CandidateCreate,
    CandidateUpdate,
    CandidateResponse,
    ApplicationCreate,
    ApplicationUpdate,
    ApplicationResponse,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectListResponse,
    PositionCreate,
    PositionUpdate,
    PositionResponse,
    ProjectSummaryResponse,
    PositionInsightsResponse,
    PositionGroupResponse,
    InsightScores,
    GroupAnalysisResponse,
    TechnicalAIResponse,
    RiskBreakdownResponse,
    TechStats,
    AIStats,
)
from app.schemas.settings import (
    ChangePasswordRequest,
    AdminProfileUpdate,
    OrganizationSettingsUpdate,
    PreferencesUpdate,
    AdminSettingsResponse,
)
from app.schemas.analytics import (
    OverviewStats,
    GroupStatusCount,
    StageCount,
    ProjectPerformance,
    RecentActivity,
    WeeklyTrend,
    RecruiterAnalyticsResponse,
)

__all__ = [
    # Auth
    "LoginRequest",
    "TokenResponse",
    "TokenPayload",
    "RefreshRequest",
    "UserResponse",
    "AdminLoginResponse",
    "AdminLoginResponseUser",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "CandidateLoginRequest",
    "CandidateAuthResponse",
    # Candidate
    "CandidateCreate",
    "CandidateUpdate",
    "CandidateResponse",
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationResponse",
    # Project
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectListResponse",
    "PositionCreate",
    "PositionUpdate",
    "PositionResponse",
    # Admin
    "GlobalStatsResponse",
    "PipelineStatsResponse",
    "HealthAnalyticsResponse",
    "PaymentMethodResponse",
    "MemberStatsResponse",
    "MemberPrivilegesResponse",
    "MemberPrivilegesUpdate",
    "MemberRegisterRequest",
    "MemberRegisterResponse",
    "PaymentMethodCreate",
    "SubscriptionUpgradeRequest",
    "ProjectSummaryResponse",
    "PositionInsightsResponse",
    "PositionGroupResponse",
    "InsightScores",
    "GroupAnalysisResponse",
    "TechnicalAIResponse",
    "RiskBreakdownResponse",
    "TechStats",
    "AIStats",
    # Settings
    "ChangePasswordRequest",
    "AdminProfileUpdate",
    "OrganizationSettingsUpdate",
    "PreferencesUpdate",
    "AdminSettingsResponse",
    # Analytics
    "OverviewStats",
    "GroupStatusCount",
    "StageCount",
    "ProjectPerformance",
    "RecentActivity",
    "WeeklyTrend",
    "RecruiterAnalyticsResponse",
]
