from app.schemas.admin import (
    GlobalStatsResponse, PipelineStatsResponse, HealthAnalyticsResponse, 
    PaymentMethodResponse, MemberStatsResponse, MemberPrivilegesResponse, 
    MemberPrivilegesUpdate, MemberRegisterRequest, MemberRegisterResponse,
    PaymentMethodCreate, SubscriptionUpgradeRequest, NotificationResponse,
    ApprovalRequestResponse, ApprovalDecisionRequest
)
from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    TokenPayload,
    RefreshRequest,
    UserResponse,
    AdminLoginResponse,
    AdminLoginResponseUser,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    CandidateLoginRequest,
    CandidateAuthResponse,
    LogoutResponse,
)
from app.schemas.candidate import (
    CandidateCreate,
    CandidateUpdate,
    CandidateResponse,
    ApplicationCreate,
    ApplicationUpdate,
    ApplicationResponse,
    CandidateUploadResponse,
)
from app.schemas.project import (
    ProjectCreate,
    ProjectUpdate,
    ProjectResponse,
    ProjectListResponse,
    PositionCreate,
    PositionUpdate,
    PositionResponse,
    PositionCandidateResponse,
    PositionDetailsResponse,
    ApplicationScoreBreakdownResponse,
    ProjectSummaryResponse,
    PositionInsightsResponse,
    PositionGroupResponse,
    InsightScores,
    GroupAnalysisResponse,
    TechnicalAIResponse,
    RiskBreakdownResponse,
    TechStats,
    AIStats,
)
from app.schemas.settings import (
    ChangePasswordRequest,
    AdminProfileUpdate,
    OrganizationSettingsUpdate,
    PreferencesUpdate,
    AdminSettingsResponse,
    RecruiterSettingsResponse,
    RecruiterProfileUpdate,
    RecruiterPreferencesUpdate,
    RecruiterAIPipelineUpdate,
)
from app.schemas.analytics import (
    OverviewStats,
    GroupStatusCount,
    StageCount,
    ProjectPerformance,
    RecentActivity,
    WeeklyTrend,
    RecruiterAnalyticsResponse,
)

from app.schemas.group import (
    GroupDetailResponse,
    GroupStatsResponse,
    CandidateProgressResponse,
    CandidateProgressItem,
    StartStageRequest,
    StartStageResponse,
    ActivityLogResponse,
    AssessmentMonitoringResponse,
    AssignInterviewRequest,
    AssignInterviewResponse,
    AcceptanceCriteriaUpdate,
    AcceptanceCriteriaUpdateResponse,
    CandidateNoteCreate,
    CandidateNoteResponse,
    CandidateDetailResponse,
    IntegrityFlagsResponse,
    ExportGroupRequest,
    GroupCreateRequest,
)

from app.schemas.recruiter_extra import (
    FilterTemplateResponse,
    FilterTemplateCreate,
    AIGenerateQuestionRequest,
    AIRefineQuestionRequest,
)

__all__ = [
    # Auth
    "LoginRequest",
    "TokenResponse",
    "TokenPayload",
    "RefreshRequest",
    "UserResponse",
    "AdminLoginResponse",
    "AdminLoginResponseUser",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "CandidateLoginRequest",
    "CandidateAuthResponse",
    "LogoutResponse",
    # Candidate
    "CandidateCreate",
    "CandidateUpdate",
    "CandidateResponse",
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationResponse",
    "CandidateUploadResponse",
    # Project
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectResponse",
    "ProjectListResponse",
    "PositionCreate",
    "PositionUpdate",
    "PositionResponse",
    "PositionCandidateResponse",
    "PositionDetailsResponse",
    "ApplicationScoreBreakdownResponse",
    # Admin
    "GlobalStatsResponse",
    "PipelineStatsResponse",
    "HealthAnalyticsResponse",
    "PaymentMethodResponse",
    "MemberStatsResponse",
    "MemberPrivilegesResponse",
    "MemberPrivilegesUpdate",
    "MemberRegisterRequest",
    "MemberRegisterResponse",
    "PaymentMethodCreate",
    "SubscriptionUpgradeRequest",
    "NotificationResponse",
    "ApprovalRequestResponse",
    "ApprovalDecisionRequest",
    "ProjectSummaryResponse",
    "PositionInsightsResponse",
    "PositionGroupResponse",
    "InsightScores",
    "GroupAnalysisResponse",
    "TechnicalAIResponse",
    "RiskBreakdownResponse",
    "TechStats",
    "AIStats",
    # Settings
    "ChangePasswordRequest",
    "AdminProfileUpdate",
    "OrganizationSettingsUpdate",
    "PreferencesUpdate",
    "AdminSettingsResponse",
    "RecruiterSettingsResponse",
    "RecruiterProfileUpdate",
    "RecruiterPreferencesUpdate",
    "RecruiterAIPipelineUpdate",
    # Analytics
    "OverviewStats",
    "GroupStatusCount",
    "StageCount",
    "ProjectPerformance",
    "RecentActivity",
    "WeeklyTrend",
    "RecruiterAnalyticsResponse",
    # Group management
    "GroupDetailResponse",
    "GroupStatsResponse",
    "CandidateProgressResponse",
    "CandidateProgressItem",
    "StartStageRequest",
    "StartStageResponse",
    "ActivityLogResponse",
    "AssessmentMonitoringResponse",
    "AssignInterviewRequest",
    "AssignInterviewResponse",
    "AcceptanceCriteriaUpdate",
    "AcceptanceCriteriaUpdateResponse",
    "CandidateNoteCreate",
    "CandidateNoteResponse",
    "CandidateDetailResponse",
    "IntegrityFlagsResponse",
    "ExportGroupRequest",
    "GroupCreateRequest",
    # Recruiter Extra
    "FilterTemplateResponse",
    "FilterTemplateCreate",
    "AIGenerateQuestionRequest",
    "AIRefineQuestionRequest",
]
